### ISSUE TITLE
not working with cordova 4.0.1

### ISSUE THREAD

**Issue by akralj** [an-rahulpandey/ios-audio-picker#8]
Hi,
made a new project and added your plugin. get this error:
/Users/a/dev/musica/cordova/platforms/ios/Musica/Plugins/me.rahul.plugins.audio-picker/iOSAudioPicker.m:164:58: error: no visible @interface for 'NSData' declares the selector
      'base64EncodedString'
                            [songInfo setObject:[imgData base64EncodedString] forKey:@"image"];

are there any other plugins i need to add?
any help would be highly appreciated.
thanks andrej

**Comment by an-rahulpandey** [comment]
I think the error is coming because of the last pull request. I still have
to see the code. Try reverting back that line with the old code.

**Comment by akralj** [comment]
there is no code of mine involved. I just used your demo files.
its on line :
https://github.com/an-rahulpandey/ios-audio-picker/blob/master/src/ios/iOSAudioPicker.m#L164

and the reason is because cordova 4.x got rid of the base64 library you where using. 
you can close the issue, because i will be using an other library. 

thanks anyway.

**Comment by an-rahulpandey** [comment]
Yeah, you are right, sorry for it. I got it mixed up with this - 
[https://github.com/an-rahulpandey/cordova-plugin-mediapicker](https://github.com/an-rahulpandey/cordova-plugin-mediapicker)

Can you try that plugin and let me know if it works or not?

**Comment by thaarok** [comment]
Confirmed - works in current https://github.com/an-rahulpandey/cordova-plugin-mediapicker (4f4eb62)
(while with this plugin cannot be compiled because error above)
